name: Deploy via git-ftp
on: 
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: git-ftp push
      uses: sebastianpopp/git-ftp-action@releases/v3
      with:
        url: "ftp://ftp.calisaurus.net"
        user: githubactionsftp
        password: ${{ secrets.FTP_PASSWORD }}